// Code generated by Kitex v0.7.2. DO NOT EDIT.

package userserviec

import (
	"context"
	userservice "github.com/Nero011/cloudStorage/server/cmd/user/kitex_gen/userservice"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return userServiecServiceInfo
}

var userServiecServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "UserServiec"
	handlerType := (*userservice.UserServiec)(nil)
	methods := map[string]kitex.MethodInfo{
		"Register": kitex.NewMethodInfo(registerHandler, newUserServiecRegisterArgs, newUserServiecRegisterResult, false),
		"Login":    kitex.NewMethodInfo(loginHandler, newUserServiecLoginArgs, newUserServiecLoginResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "userservice",
		"ServiceFilePath": `../../idl/rpc/user.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.7.2",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*userservice.UserServiecRegisterArgs)
	realResult := result.(*userservice.UserServiecRegisterResult)
	success, err := handler.(userservice.UserServiec).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiecRegisterArgs() interface{} {
	return userservice.NewUserServiecRegisterArgs()
}

func newUserServiecRegisterResult() interface{} {
	return userservice.NewUserServiecRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*userservice.UserServiecLoginArgs)
	realResult := result.(*userservice.UserServiecLoginResult)
	success, err := handler.(userservice.UserServiec).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiecLoginArgs() interface{} {
	return userservice.NewUserServiecLoginArgs()
}

func newUserServiecLoginResult() interface{} {
	return userservice.NewUserServiecLoginResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *userservice.RegisterRequest) (r *userservice.RegisterResponse, err error) {
	var _args userservice.UserServiecRegisterArgs
	_args.Req = req
	var _result userservice.UserServiecRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *userservice.LoginRequest) (r *userservice.LoginResponse, err error) {
	var _args userservice.UserServiecLoginArgs
	_args.Req = req
	var _result userservice.UserServiecLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
